# appspec.yaml
version: 1
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "taskDefinition"
        LoadBalancerInfo:
          ContainerName: "project-app"
          ContainerPort: 8080