# appspec.yaml
version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "project-app-task"
        LoadBalancerInfo:
          ContainerName: "project-app"
          ContainerPort: 8080