# Name of your GitHub Actions Workflow
name: Build and Push Docker Image to ECR

# This workflow runs on any push to the 'main' branch
on:
  push:
    branches:
      - "main"

# These are the jobs that will run
jobs:
  build-and-push:
    name: Build and Push to ECR
    runs-on: ubuntu-latest # Use a standard Linux runner

    # IMPORTANT: These permissions are required for OIDC authentication
    permissions:
      id-token: write
      contents: read

    steps:
      # Step 1: Check out your application code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      # Step 3: Build the JAR with Maven
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Configure AWS credentials using the OIDC role
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: 'arn:aws:iam::677276091734:role/YourGitHubOidcRoleName'
          aws-region: 'eu-central-1'

      # Step 5: Log in to the Amazon ECR registry
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Step 6: Build the Docker image, tag it, and push it to ECR
      - name: Build, tag, and push image to Amazon ECR
        env:
          # Get the ECR registry URL from the previous login step
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          # Use your ECR repository name from CloudFormation
          ECR_REPOSITORY: 'my-project-app'
          # Use the GitHub commit hash as the image tag for uniqueness
          #IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest .